version: '3.1'

services:
  db.nf:
    image: mysql:5.7
    env_file: .env
    volumes:
      - ./mysql_nf-datadir:/var/lib/mysql:z
      - ./mysql_nf-shr:/shr:z
      - ./mysql_nf-autoload:/docker-entrypoint-initdb.d:ro
      - ./mysql_nf-conf.d:/etc/mysql/conf.d:z
  as:
    image: dina/naturalist_enhanced:v0.1
    environment:
       - VIRTUAL_HOST=beta-naturforskaren.dina-web.net
       - VIRTUAL_PORT=8080
    volumes:
      - ./srv/data:/opt/data/nf
      - ./srv/releases:/opt/jboss/wildfly/releases
      - ./srv/log:/opt/jboss/wildfly/nf-logs
    links:
      - db.nf:dbnf

networks:
  default:
    external:
      name: proxydocker_default
