fs_db:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql:z
    - ./mysql-shr:/shr:z
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql-conf.d:/etc/mysql/conf.d:z

fs_naturalist:
  image: tianon/true
  volumes:
    - ./srv/data:/opt/data
    - ./srv/deployments:/opt/jboss/wildfly/standalone/deployments:z

db:
  image: mysql:5.5
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=taxonpages_v2
    - MYSQL_USER=naturalist
    - MYSQL_PASSWORD=passw0rd12
  ports:
    - "13306:3306"
  volumes_from:
    - fs_db

as:
  build: ./wildfly-custom
  environment:
    - TZ=Europe/Stockholm
    - VIRTUAL_HOST=test.naturforskaren.se
  ports:
    - "18080:8080"
    - "19990:9990"
  volumes_from:
    - fs_naturalist
  links:
    - db

ws:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  links:
    - as
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

