fs_db.nf:
  image: tianon/true
  volumes:
    - ./mysql_nf-datadir:/var/lib/mysql:z
    - ./mysql_nf-shr:/shr:z
    - ./mysql_nf-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql_nf-conf.d:/etc/mysql/conf.d:z

fs_naturalist:
  image: tianon/true
  volumes:
    - ./srv/data:/opt/data
    - ./srv/deployments:/opt/jboss/wildfly/standalone/deployments:z

fs_ws:
  image: tianon/true
  volumes:
    - ./nginx-html:/usr/share/nginx/html:z
    - ./nginx-conf:/etc/nginx/conf.d:z
    - ./nginx-certs:/etc/nginx/ssl:z
    - ./nginx-logs:/etc/nginx/logs:z

db.nf:
  image: mysql:5.5
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=supersecret
    - MYSQL_DATABASE=taxonpages_v2
    - MYSQL_USER=naturalist
    - MYSQL_PASSWORD=passw0rd12
  ports:
    - "13306:3306"
  volumes_from:
    - fs_db.nf

as:
  build: ./wildfly-custom
  ports:
    - "8080"
    - "9990"
  volumes_from:
    - fs_naturalist
  links:
    - db.nf:db

ws:
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs_ws
  links:
    - as
